title: Ronee Medhi # your name (or website title) here
logo: "/profile.png?raw=true" # your photo (or logo) here
description: > # yuor text below (remove <br> elements if you don't need line breaks)
Product Manager
 <br><br>
 <a href="mailto:roneemedhi@gmail.com">roneemedhi@gmail.com</a>
 <br>
 <a href="https://www.linkedin.com/in/roneemedhi/">LinkedIn Profile</a>
 <br>
 <a href="https://github.com/roneemedhi/">GitHub</a>
 <br>
 <a href="https://roneemedhi.wixsite.com/website">Wixsite</a>
 <br>
 <a href="https://roneemedhi.medium.com/">Medium</a>
theme: jekyll-theme-cayman
