logo: "/profile.png?raw=true" 
description: >
 Product Manager
  <br><br>
  <a href="mailto:roneemedhi@gmail.com">roneemedhi@gmail.com</a>
  <br>
  <a href="https://www.linkedin.com/in/roneemedhi/">LinkedIn Profile</a>
  <br>
  <a href="https://roneemedhi.medium.com/">Medium</a>
  <br>
  <a href="https://roneemedhi.wixsite.com/website">Wixsite</a>
  <br>
  <a href="https://github.com/roneemedhi/">GitHub</a>
theme: jekyll-theme-cayman
