title: Ronee Medhi # your name (or website title) here
logo: "/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Product Leader
  <br><br>
  <a href="https://linktr.ee/rmedhi9">Linktree</a>
  <br>
  <a href="https://ronee-medhi.netlify.app/">Netlify</a>
  <br>
  <a href="https://github.com/roneemedhi/">GitHub</a>
theme: jekyll-theme-minimal
